### ISSUE TITLE
Enter current address or geolocate

### ISSUE THREAD

**Issue by ssyberg** [googlecodelabs/google-maps-simple-store-locator#5]
Sorry if I'm missing this, but I don't see any mention in the tutorials about the user entering their address or using geolocation to show the stores near them... is this correct?

**Comment by wangela** [comment]
Correct, the map produced in this codelab as it stands today merely displays all locations that exist, not finding the closest one to a specific location. To add the feature you describe, you may use a combination of these JavaScript services:

- [Geolocation](https://developers.google.com/maps/documentation/javascript/geolocation) to find the current location of the device
- [Autocomplete for Addresses](https://developers.google.com/maps/documentation/javascript/places-autocomplete#video) to allow the user to specify a starting point instead of using current location
- [Distance Matrix service](https://developers.google.com/maps/documentation/javascript/distancematrix) to calculate distances and travel times from one point to all the locations so you can pick display locations ranked by shortest distance or travel time

The documentation linked above includes sample code that you can use to implement each of the features.
